name: Android CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gradle caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')}}
          restore-keys: |
            ${{runner.os}}-gradle-

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create LOCAL_PROPERTIES
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: GOMS Android CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ GOMS-Android-CI 성공! ✅
          webhook: ${{ secrets.GOMS_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.SUCCESS_IMAGE }}
          description: "성공했습니다!"
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: GOMS CI 봇

      - name: GOMS Android CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗️ GOMS-Android-CI 실패! ❗️
          webhook: ${{ secrets.GOMS_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.FAILED_IMAGE }}
          description: "성공해서 돌아오겠습니다!"
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: GOMS CI 봇
